export interface Key {
  code: string;
  name: string;
  columnSpan: number;
  sameColumn: boolean;
  rowSpan: number;
  rowStartAt: number;
}

export const data = [
  [
    {
      code: '`',
      name: '`',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '1',
      name: '1',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '2',
      name: '2',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '3',
      name: '3',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '4',
      name: '4',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '5',
      name: '5',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '6',
      name: '6',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '7',
      name: '7',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '8',
      name: '8',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '9',
      name: '9',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '0',
      name: '0',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '-',
      name: '-',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '=',
      name: '=',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'delete',
      name: 'delete',
      columnSpan: 6,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
  ],
  [
    {
      code: 'tab',
      name: 'tab',
      columnSpan: 6,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'q',
      name: 'q',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'w',
      name: 'w',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'e',
      name: 'e',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'r',
      name: 'r',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 't',
      name: 't',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'y',
      name: 'y',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'u',
      name: 'u',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'i',
      name: 'i',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'o',
      name: 'o',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'p',
      name: 'p',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '[',
      name: '[',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: ']',
      name: ']',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '\\',
      name: '\\',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
  ],
  [
    {
      code: 'caps lock',
      name: 'caps lock',
      columnSpan: 7,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'a',
      name: 'a',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 's',
      name: 's',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'd',
      name: 'd',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'f',
      name: 'f',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'g',
      name: 'g',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'h',
      name: 'h',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'j',
      name: 'j',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'k',
      name: 'k',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'l',
      name: 'l',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: ';',
      name: ';',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: "'",
      name: "'",
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'enter',
      name: 'enter',
      columnSpan: 9,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
  ],
  [
    {
      code: 'left shift',
      name: 'shift',
      columnSpan: 10,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'z',
      name: 'z',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'x',
      name: 'x',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'c',
      name: 'c',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'v',
      name: 'v',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'b',
      name: 'b',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'n',
      name: 'n',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'm',
      name: 'm',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: ',',
      name: ',',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '.',
      name: '.',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: '/',
      name: '/',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'right shift',
      name: 'shift',
      columnSpan: 10,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
  ],
  [
    {
      code: 'fn',
      name: 'fn',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'left ctrl',
      name: 'ctrl',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'left alt',
      name: 'alt',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'left command',
      name: 'cmd',
      columnSpan: 5,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'space',
      name: '',
      columnSpan: 20,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'right command',
      name: 'cmd',
      columnSpan: 5,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'right alt',
      name: 'alt',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'left',
      name: 'left',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'up',
      name: 'up',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 2,
      rowStartAt: 0,
    },
    {
      code: 'down',
      name: 'down',
      columnSpan: 4,
      sameColumn: true,
      rowSpan: 2,
      rowStartAt: 2,
    },
    {
      code: 'right',
      name: 'right',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
  ],
];
