export interface Key {
  code: string;
  name: string;
  columnSpan: number;
  sameColumn: boolean;
  rowSpan: number;
  rowStartAt: number;
}

export const data = [
  [
    {
      code: 'Backquote',
      name: '`',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Digit1',
      name: '1',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Digit2',
      name: '2',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Digit3',
      name: '3',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Digit4',
      name: '4',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Digit5',
      name: '5',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Digit6',
      name: '6',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Digit7',
      name: '7',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Digit8',
      name: '8',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Digit9',
      name: '9',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Digit0',
      name: '0',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Minus',
      name: '-',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Equal',
      name: '=',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Backspace',
      name: 'delete',
      columnSpan: 6,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
  ],
  [
    {
      code: 'Tab',
      name: 'tab',
      columnSpan: 6,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyQ',
      name: 'q',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyW',
      name: 'w',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyE',
      name: 'e',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyR',
      name: 'r',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyT',
      name: 't',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyY',
      name: 'y',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyU',
      name: 'u',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyI',
      name: 'i',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyO',
      name: 'o',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyP',
      name: 'p',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'BracketLeft',
      name: '[',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'BracketRight',
      name: ']',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Backslash',
      name: '\\',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
  ],
  [
    {
      code: 'CapsLock',
      name: 'caps lock',
      columnSpan: 7,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyA',
      name: 'a',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyS',
      name: 's',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyD',
      name: 'd',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyF',
      name: 'f',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyG',
      name: 'g',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyH',
      name: 'h',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyJ',
      name: 'j',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyK',
      name: 'k',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyL',
      name: 'l',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Semicolon',
      name: ';',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Quote',
      name: "'",
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Enter',
      name: 'enter',
      columnSpan: 9,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
  ],
  [
    {
      code: 'ShiftLeft',
      name: 'shift',
      columnSpan: 10,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyZ',
      name: 'z',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyX',
      name: 'x',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyC',
      name: 'c',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyV',
      name: 'v',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyB',
      name: 'b',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyN',
      name: 'n',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'KeyM',
      name: 'm',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Comma',
      name: ',',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Period',
      name: '.',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Slash',
      name: '/',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'ShiftRight',
      name: 'shift',
      columnSpan: 10,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
  ],
  [
    {
      code: 'fn',
      name: 'fn',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'ControlLeft',
      name: 'ctrl',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'AltLeft',
      name: 'alt',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'MetaLeft',
      name: 'cmd',
      columnSpan: 5,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'Space',
      name: '',
      columnSpan: 20,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'MetaRight',
      name: 'cmd',
      columnSpan: 5,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'AltRight',
      name: 'alt',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'ArrowLeft',
      name: 'left',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
    {
      code: 'ArrowUp',
      name: 'up',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 2,
      rowStartAt: 0,
    },
    {
      code: 'ArrowDown',
      name: 'down',
      columnSpan: 4,
      sameColumn: true,
      rowSpan: 2,
      rowStartAt: 2,
    },
    {
      code: 'ArrowRight',
      name: 'right',
      columnSpan: 4,
      sameColumn: false,
      rowSpan: 4,
      rowStartAt: 0,
    },
  ],
];
